version: "3.9"

services:
  ft_ping:
    image: my_ping:latest
    build: .
    command: tail -f /dev/null
    privileged: true
    develop:
      watch:
        - action: sync
          path: ./
          target: /ft_ping
    networks:
      - network1

networks:
  network1:
